/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./src/components/common/AppBar.vue')['default']
    DashboardContent: typeof import('./src/components/dashboard/DashboardContent.vue')['default']
    DashboardSideBar: typeof import('./src/components/dashboard/DashboardSideBar.vue')['default']
    FooterBar: typeof import('./src/components/editor/FooterBar.vue')['default']
    FormContainer: typeof import('./src/components/common/FormContainer.vue')['default']
    GridItem: typeof import('./src/components/common/GridItem.vue')['default']
    LeftSideBar: typeof import('./src/components/editor/LeftSideBar.vue')['default']
    LeftSideBarPhotos: typeof import('./src/components/editor/leftsidebar/LeftSideBarPhotos.vue')['default']
    LeftSideBarTemplates: typeof import('./src/components/editor/leftsidebar/LeftSideBarTemplates.vue')['default']
    LeftSideBarUploads: typeof import('./src/components/editor/leftsidebar/LeftSideBarUploads.vue')['default']
    LibraryWrapper: typeof import('./src/components/common/LibraryWrapper.vue')['default']
    MainContent: typeof import('./src/components/editor/MainContent.vue')['default']
    RightSideBar: typeof import('./src/components/editor/RightSideBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolBar: typeof import('./src/components/editor/ToolBar.vue')['default']
    TopBar: typeof import('./src/components/editor/TopBar.vue')['default']
    UserMenu: typeof import('./src/components/common/UserMenu.vue')['default']
  }
}
